class Config:
    SAFE_FIELD_SPACE = 5
    CLOCK_TICK = 10
    FOOD_COLOR = (220, 0, 0)
    SNAKE_COLOR = (0, 220, 0)
    HEAD_COLOR = (90, 60, 90)
    BG_COLOR = (50, 50, 50)
    RECT_DIM = 100
    SCREEN_WIDTH = 700
    SCREEN_HEIGHT = 600
    SNAKE_INIT_LENGTH = 3
    SNAKE_INIT_X = (SNAKE_INIT_LENGTH + 1) * RECT_DIM
    SNAKE_INIT_Y = SCREEN_HEIGHT / 2 if not SCREEN_HEIGHT % 200 else (SCREEN_HEIGHT / 2) - 50
    AI = True
