class Config:
    CLOCK_TICK = 10
    FOOD_COLOR = (220, 0, 0)
    SNAKE_COLOR = (0, 220, 0)
    BG_COLOR = (50, 50, 50)
    RECT_DIM = 100
    SCREEN_WIDTH = 600
    SCREEN_HEIGHT = 600
    SNAKE_INIT_LENGTH = 2
    SNAKE_INIT_X = (SNAKE_INIT_LENGTH + 1) * RECT_DIM
    SNAKE_INIT_Y = SCREEN_HEIGHT / 2
    AI = True
